### ISSUE TITLE
Compilation an Iteration Behind

### ISSUE THREAD

**Issue by wbrickner** [BrainiumLLC/cargo-mobile#13] opened 2021-01-07 09:10 UTC
I've noticed that when I make a change to my `lib.rs`, and then run `cargo android run`, the old version of my code runs, not the new version. Then upon second invocation the new version runs.

This sounds very similar to what @Zeerooth experienced in #2 where the first run fails, but the second run includes the `.so` library. 

I suspect some compilation step lags behind.

**Comment by Zeerooth** [comment] 2021-01-07 18:20
I looked a bit more into the logs I've provided in #2 and there are a lot of differences, which are hard to filter, so I don't know yet what is the cause of the problem. I attached ```diff``` of both logs [here](https://github.com/BrainiumLLC/cargo-mobile/files/5783265/diff.txt) if you want to take a look. 

So far I've noticed this one thing - SDK is not parsed in the first run:
```
Parsing the SDK, no caching allowed
SDK initialized in 1 ms
```

But in the second, it is:
```
Parsing the SDK, no caching allowed
Parsing /home/radek/Android/Sdk/build-tools/28.0.3/package.xml
Parsing /home/radek/Android/Sdk/build-tools/29.0.3/package.xml
Parsing /home/radek/Android/Sdk/build-tools/30.0.3/package.xml
Parsing /home/radek/Android/Sdk/cmake/3.10.2.4988404/package.xml
Parsing /home/radek/Android/Sdk/emulator/package.xml
Parsing /home/radek/Android/Sdk/ndk-bundle/package.xml
Parsing /home/radek/Android/Sdk/ndk/22.0.7026061/package.xml
Parsing /home/radek/Android/Sdk/patcher/v4/package.xml
Parsing /home/radek/Android/Sdk/platform-tools/package.xml
Parsing /home/radek/Android/Sdk/platforms/android-28/package.xml
Parsing /home/radek/Android/Sdk/platforms/android-29/package.xml
Parsing /home/radek/Android/Sdk/platforms/android-30/package.xml
Parsing /home/radek/Android/Sdk/sources/android-30/package.xml
Parsing /home/radek/Android/Sdk/system-images/android-30/google_apis/x86/package.xml
Parsing /home/radek/Android/Sdk/tools/package.xml
SDK initialized in 253 ms
```

I've also saved both ```gen/android/<project name>/app/build/``` and ```target/``` directories after each ```cargo android run```, then ran ```diff -qr run_0/ run_1/ ``` on them and these are the results:
```
Files run_0/build/intermediates/incremental/arm64Debug-mergeJniLibs/merge-state and run_1/build/intermediates/incremental/arm64Debug-mergeJniLibs/merge-state differ
Files run_0/build/intermediates/incremental/mergeArm64DebugJniLibFolders/merger.xml and run_1/build/intermediates/incremental/mergeArm64DebugJniLibFolders/merger.xml differ
Files run_0/build/intermediates/incremental/packageArm64Debug/tmp/arm64Debug/dex-renamer-state.txt and run_1/build/intermediates/incremental/packageArm64Debug/tmp/arm64Debug/dex-renamer-state.txt differ
Files run_0/build/intermediates/incremental/packageArm64Debug/tmp/arm64Debug/file-input-save-data.txt and run_1/build/intermediates/incremental/packageArm64Debug/tmp/arm64Debug/file-input-save-data.txt differ
Only in run_1/build/intermediates/merged_jni_libs/arm64Debug/out/arm64-v8a: libcargo_mobile_test.so
Only in run_1/build/intermediates/transforms/mergeJniLibs/arm64/debug/0/lib/arm64-v8a: libcargo_mobile_test.so
Files run_0/build/intermediates/transforms/mergeJniLibs/arm64/debug/__content__.json and run_1/build/intermediates/transforms/mergeJniLibs/arm64/debug/__content__.json differ
Only in run_1/build/intermediates/transforms/stripDebugSymbol/arm64/debug/0/lib/arm64-v8a: libcargo_mobile_test.so
Files run_0/build/intermediates/transforms/stripDebugSymbol/arm64/debug/__content__.json and run_1/build/intermediates/transforms/stripDebugSymbol/arm64/debug/__content__.json differ
Files run_0/build/outputs/apk/arm64/debug/app-arm64-debug.apk and run_1/build/outputs/apk/arm64/debug/app-arm64-debug.apk differ
```

These are the most interesting differences (I think):
```
Only in run_1/build/intermediates/merged_jni_libs/arm64Debug/out/arm64-v8a: libcargo_mobile_test.so
Only in run_1/build/intermediates/transforms/mergeJniLibs/arm64/debug/0/lib/arm64-v8a: libcargo_mobile_test.so
Only in run_1/build/intermediates/transforms/stripDebugSymbol/arm64/debug/0/lib/arm64-v8a: libcargo_mobile_test.so
```

Seems like required .so library is missing after the first run and is only generated later

Alright, that's all for now, I'll look into the code and I'll keep posting updates when I discover something new

**Comment by Zeerooth** [comment] 2021-01-08 00:33
Okay, so it seems like the problem comes from the gradle workflow in this project - normally, it's possible to put native libraries in ```app/src/main/jniLibs/<arch>/<library_name>.so```, which automatically gets picked up and included in funal build. Yes, cargo-mobile has a step to generate this library and later simlink it from /target directory, but the problem is that it happens too late and gradle doesn't pick it up (it only does in the next run after that, because ```cargo android run``` is invoked when this library is already present). This is also why each time old library is being linked and the old code is run.

Unfortunately, I'm not that experienced with gradle so I would greatly appreciate it if somebody could let me know if it's possible to move rust build step up in the workflow, before whole app/build directory is being generated. If it's not possible though I guess another solution would be to just symlink .so library to those directories in cargo-mobile code (examples):
```
build/intermediates/merged_jni_libs/arm64Debug/out/arm64-v8a: libcargo_mobile_test.so
build/intermediates/transforms/mergeJniLibs/arm64/debug/0/lib/arm64-v8a: libcargo_mobile_test.so
build/intermediates/transforms/stripDebugSymbol/arm64/debug/0/lib/arm64-v8a: libcargo_mobile_test.so 
```
This method *should* work as the apk is actually assembled in the last gradle step, so the library should be included in the build.
I'll get to work on this later if it isn't possible to be fixed in build.gradle scripts

**Closed** 2021-01-22 21:20 UTC
Labels: status: in progress, target: Android, type: bug
